#!/bin/bash

ls -l app/ static/ \
| egrep -o '../_sources/(([a-zA-Z][^-]*-)*)([0-9][^/]*)' \
| sed -r 's|../_sources/(([a-zA-Z][^-]*-)*)([0-9].*)|\1 \3|' \
| sed 's/- / /' \
| sort -u \
| while read PKG VER; do
    curl 2>/dev/null https://pypi.python.org/pypi/$PKG/ \
    | egrep -o 'https://pypi.python.org/packages[^"]+\.(tar.gz|zip|bz2)#md5=.{32}' \
    | egrep -v -- "-$VER\." | head -1
done
