version: '3.4'
services:

  leprikon:
    image: misli/svcletovice:testing
    depends_on:
      - db
      - memcached
    environment:
      DEBUG: TEMPLATE
      SECRET_KEY: secretkey
      DATABASE_ENGINE: django.db.backends.mysql
      DATABASE_HOST: ''
      DATABASE_NAME: svcletovice
      DATABASE_PASSWORD: svcletovicepassword
      DATABASE_USER: svcletovice
      MEMCACHED_LOCATION: memcached:11211
    ports:
      - 127.0.0.1:80:80
    restart: unless-stopped
    volumes:
      - ./.ipython:/root/.ipython:z
      - ./svcletovice:/app/svcletovice:ro
      - ./data:/app/data:z
      - ./htdocs/media:/app/htdocs/media:z
      - db:/var/run/mysqld:z

  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: svcletovice
      MYSQL_PASSWORD: svcletovicepassword
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: svcletovice
    ports:
      - 127.0.0.1:3306:3306
    restart: unless-stopped
    volumes:
      - db:/var/run/mysqld:z
      - ./mysql:/var/lib/mysql:z

  memcached:
    image: memcached
    ports:
      - 127.0.0.1:11211:11211
    restart: unless-stopped

volumes:
  db:
