version: '3.4'
services:

  leprikon:
    image: misli/svcletovice
    build: .
    depends_on:
      - mysql
      - redis
      - smtp
    environment:
      DATABASE_ENGINE: django.db.backends.mysql
      DATABASE_HOST: ''
      DATABASE_NAME: svcletovice
      DATABASE_USER: svcletovice
      DATABASE_PASSWORD: dbpassword
      EMAIL_HOST: smtp
      EMAIL_HOST_USER: svcletovice
      EMAIL_HOST_PASSWORD: emailpassword
      EMAIL_SUBJECT_PREFIX: '[Letokruh]'
      CACHE_LOCATION: unix:///var/run/redis/redis.sock
      SECRET_KEY: secretkey
      SERVER_EMAIL: '"SVČ Letokruh" <muj-letokruh@svcletovice.cz>'
    ports:
      - 127.0.0.1:10000:80
    volumes:
      - ./data:/app/data
      - ./letsencrypt:/etc/letsencrypt
      - ./media:/app/htdocs/media
      - ./wordpress:/app/htdocs/wordpress
      - mysql:/var/run/mysqld
      - redis:/var/run/redis

  redis:
    image: redis
    command: bash -c "chmod 0777 /var/run/redis && redis-server --appendonly yes --unixsocket /var/run/redis/redis.sock --unixsocketperm 777"
    volumes:
      - ./redis:/data
      - redis:/var/run/redis

  mysql:
    image: mariadb
    environment:
      MYSQL_DATABASE: svcletovice
      MYSQL_USER: svcletovice
      MYSQL_PASSWORD: dbpassword
      MYSQL_ROOT_PASSWORD: rootdbpassword
    volumes:
      - mysql:/var/run/mysqld
      - ./mysql:/var/lib/mysql

  smtp:
    image: catatnight/postfix
    environment:
      maildomain: svcletovice.cz
      smtp_user: svcletovice:emailpassword
    stdin_open: true
    tty: true
    volumes:
      - ./dkim:/etc/opendkim/domainkeys

volumes:
  mysql:
  redis:
