#!/bin/bash

letsencrypt certonly --webroot -w /srv/letsencrypt/htdocs -d svcletovice.cz -d www.svcletovice.cz -d svc-letovice.cz -d www.svc-letovice.cz -d svcletokruh.cz -d www.svcletokruh.cz -d svc-letokruh.cz -d www.svc-letokruh.cz -d ddmletovice.cz -d www.ddmletovice.cz
